---
- name: Reboot if /etc/fstab was modified
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command: uptime
    
- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Restart crio
  ansible.builtin.systemd:
    name: crio
    state: restarted
    enabled: yes
