---
- name: Add Cilium Helm repository
  helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install Cilium via Helm
  helm:
    name: cilium
    chart: cilium/cilium
    namespace: kube-system
    version: "{{ cilium_version }}"
    values:
      ipam.operator.clusterPoolIPv4PodCIDRList:
        - "{{ pod_subnet }}"

- name: Template Cilium YAML with variables
  ansible.builtin.template:
    src: "templates/cilium.yaml.j2"
    dest: "/tmp/cilium.yaml"
    mode: '0644'
  tags:
    - cilium

- name: Apply Cilium YAML
  kubernetes.core.k8s:
    state: present
    src: "/tmp/cilium.yaml"
    kubeconfig: "{{ kubeconfig_path }}"
  tags:
    - cilium

#- name: Wait for Cilium pods to be ready
#  kubernetes.core.k8s_info:
#    kind: Pod
#    namespace: "{{ cilium_namespace }}"
#  register: cilium_pods
#  until: cilium_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length >= 1
#  retries: 10
#  delay: 15
#  tags:
#    - cilium

- name: Display Cilium pod statuses
  debug:
    msg: "{{ cilium_pods.resources | json_query('[*].metadata.name') }}"
  tags:
    - cilium
