---
- name: Configure Kubernetes Masters and Deploy Cilium
  hosts: masters
  become: yes
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  roles:
    - common
    - kubernetes-master
    - cilium  

- name: Configure Kubernetes Workers
  hosts: workers
  become: yes
  roles:
     - common
#    - kubernetes-worker
