---
- name: Configure Admin Node
  hosts: masters
  become: yes
  roles:
    - common

- name: Configure Kubernetes Masters
  hosts: masters
  become: yes
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  roles:
    - common
#    - kubernetes-master
#    - cilium  

- name: Configure Kubernetes Workers
  hosts: workers
  become: yes
  roles:
     - common
#     - kubernetes-worker
